from typing import List, Optional
from pydantic import BaseModel, UUID4 # For UUID validation
from app.models.review_tag import ReviewTagStatusEnum
from app.schemas.material import MaterialSetResponse # To show nested material sets

class ReviewTagBase(BaseModel):
    name: str
    status: Optional[ReviewTagStatusEnum] = ReviewTagStatusEnum.ACTIVE
    material_set_ids: Optional[List[int]] = [] # List of MaterialSet IDs to associate

class ReviewTagCreate(ReviewTagBase):
    merchant_id: int 

class ReviewTagUpdate(BaseModel): # More flexible update
    name: Optional[str] = None
    status: Optional[ReviewTagStatusEnum] = None
    material_set_ids: Optional[List[int]] = None # Allow complete replacement of associated sets

class ReviewTagResponse(BaseModel):
    id: int
    merchant_id: int
    name: str
    tag_identifier: UUID4 # This will be generated by the DB/model
    status: ReviewTagStatusEnum
    material_sets: List[MaterialSetResponse] = [] # Show associated material sets

    class Config:
        orm_mode = True
